### ISSUE TITLE
saveSVG() method doesn't work correctly

### ISSUE THREAD

**Issue by rprokopenko** [ushelp/EasyQRCodeJS-NodeJS#18] opened 2021-07-22 10:21 UTC
Hi, **saveSVG()** method doesn't work correctly.
Code: 
`const QRCode = require("easyqrcodejs-nodejs")

// Options
var options = {
	text: "www.easyproject.cn/donation",
    logo: 'https://image.flaticon.com/icons/svg/32/32441.svg',
};

// New instance with options
var qrcode = new QRCode(options);

qrcode.saveSVG({
    path: 'qrcode.svg' // file path
}).then(data=>{
   console.log("`qrcode.svg` has been Created!");
});`

Result:
![Screenshot_4](https://user-images.githubusercontent.com/64587009/126623845-e8064b05-a0e6-471b-9615-29295f1123cc.png)

But if I use the **saveImage()** method and save in png format, then everything is fine. That is, the url of the picture is correct.
Code:
`const QRCode = require("easyqrcodejs-nodejs")

// Options
var options = {
	text: "www.easyproject.cn/donation",
    logo: 'https://image.flaticon.com/icons/svg/32/32441.svg',
};

// New instance with options
var qrcode = new QRCode(options);

qrcode.saveImage({
    path: 'qrcode.png' // file path
}).then(data=>{
   console.log("`qrcode.png` has been Created!");
});`

Result:
![qrcode](https://user-images.githubusercontent.com/64587009/126624472-7f549d83-6f06-4dad-b72d-92453fecbd77.png)

Thanks in advance for the help.

**Comment by ushelp** [comment] 2021-07-22 10:48
Duplicate of #19

**Closed as completed by ushelp** 2021-07-22 10:48 UTC

**Comment by rprokopenko** [comment] 2021-07-22 11:42
Also this problem occurs when using the method toSVGText()

**Comment by ushelp** [comment] 2021-07-23 04:43
We have release a new version 4.3.4 fixed the issue, please upgrade to the latest version.
Thank you.
